//
//  HelpMainView.swift
//  Scene Machine
//
//  Created by Carlos Farini on 5/3/21.
//

import SwiftUI

struct HelpMainView: View {
    
    enum HelpSection {
        case Base
        case Noise
        case ImageFX
        case Scenes
    }
    
    @State var selection:HelpSection? = .Base
    
    var body: some View {
        NavigationView {
            
            List(selection:$selection) {
                
                NavigationLink(
                    destination: HelpFrontView(),
                    tag: HelpSection.Base,
                    selection: $selection) {
                    Label("Start", systemImage: "heart")
                }
                .tag(HelpSection.Base)
                
                NavigationLink(
                    destination: HelpNoiseView(),
                    tag: HelpSection.Noise,
                    selection: $selection) {
                    Label("Noise & Generators", systemImage: "heart")
                }
                .tag(HelpSection.Noise)
                
                NavigationLink(
                    destination: HelpImagesView(),
                    tag: HelpSection.ImageFX,
                    selection: $selection) {
                    Label("Images & Special Effects", systemImage: "heart")
                }
                .tag(HelpSection.ImageFX)
                
                NavigationLink(
                    destination: HelpSceneView(),
                    tag: HelpSection.Scenes,
                    selection: $selection) {
                    Label("Scenes", systemImage: "heart")
                }
                .tag(HelpSection.Scenes)
            }
            .frame(minWidth: 100, maxWidth: 200, alignment: .center)
        }
    }
}

struct HelpFrontView:View {
    var body: some View {
        ScrollView {
            VStack(alignment:.leading) {
                Text("Help - Start").font(.title).foregroundColor(.accentColor)
                Text("Scene Machine is composed of three main parts.")
                
                Text("Noise & Generators")
                    .foregroundColor(.blue).font(.title2).padding(6)
                
                Text("There are three views that make images from noise sources.")
                
                Group {
                    Text("Quick Noise").font(.title3).padding(6).foregroundColor(.blue)
                    
                    Text("Makes a basic perlin noise, considering only one variable: Smoothness. You may also choose the size of the image generated by going through the options of 'sizes'")
                }
                
                Group {
                    Text("SpriteKit Noise").font(.title3).padding(6).foregroundColor(.blue)
                    
                    Text("SpriteKit offers a few great ways to make noise, and Scene Machine uses it as a tool to create great textures.")
                }
                
                Divider()
                Text("Image FX").font(.title2).padding()
                Text("Scenes").font(.title2).padding()
            }
            .padding(8)
            .frame(minWidth: 200, maxWidth: 750, minHeight: 300, maxHeight: /*@START_MENU_TOKEN@*/.infinity/*@END_MENU_TOKEN@*/, alignment: .top)
        }
    }
}

struct HelpNoiseView:View {
    var body: some View {
        ScrollView {
            VStack {
                Text("Noise").font(.title).foregroundColor(.accentColor)
                Text("There are 3 noise, or pattern generators.")
                
            }
            
        }
        
    }
}

struct HelpImagesView:View {
    var body: some View {
        VStack {
            Text("Image FX")
        }
    }
}

struct HelpSceneView:View {
    var body: some View {
        VStack {
            Text("Scenes")
        }
    }
}

struct HelpMainView_Previews: PreviewProvider {
    static var previews: some View {
        HelpMainView()
    }
}
